status = error
name = HanziSpiderConfig

appenders = console, rollingfile
appender.console.type = Console
appender.console.name = STDOUT
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %-5p | %d{yyyy-MM-dd HH:mm:ss} | [%t] %C{2} (%F:%L) - %m%n

appender.rollingfile.type = RollingFile
appender.rollingfile.name = RollingFile
appender.rollingfile.fileName = logs/HanziSpider.log
appender.rollingfile.filePattern = logs/HanziSpider-%d{MM-dd-yyyy}-%i.log.gz
appender.rollingfile.layout.type = PatternLayout
appender.rollingfile.layout.pattern = %-5p | %d{yyyy-MM-dd HH:mm:ss} | [%t] %C{2} (%F:%L) - %m%n
appender.rollingfile.policies.type = Policies
appender.rollingfile.policies.time.type = TimeBasedTriggeringPolicy
appender.rollingfile.policies.size.type = SizeBasedTriggeringPolicy
appender.rollingfile.policies.size.size = 250 MB
appender.rollingfile.strategy.type = DefaultRolloverStrategy
appender.rollingfile.strategy.max = 4

rootLogger.level = info
rootLogger.appenderRefs = stdout, rolling
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.rolling.ref = RollingFile