FROM openjdk:11
COPY HanzeSpider-1.0-SNAPSHOT-jar-with-dependencies.jar /HanzeSpider-1.0-SNAPSHOT-jar-with-dependencies.jar
CMD ["java", "-jar", "/HanzeSpider-1.0-SNAPSHOT-jar-with-dependencies.jar"]
